package settings

func Names() []string {
	return names[:]
}

var names = []string{
	"adult_trade_shuffle",
	"big_poe_count",
	"blue_fire_arrows",
	"bridge",
	"bridge_hearts",
	"bridge_medallions",
	"bridge_rewards",
	"bridge_stones",
	"bridge_tokens",
	"chicken_count",
	"complete_mask_quest",
	"damage_multiplier",
	"deadly_bonks",
	"disable_trade_revert",
	"dungeon_shortcuts",
	"entrance_shuffle",
	"fix_broken_drops",
	"free_bombchu_drops",
	"free_scarecrow",
	"ganon_bosskey_hearts",
	"ganon_bosskey_medallions",
	"ganon_bosskey_rewards",
	"ganon_bosskey_stones",
	"ganon_bosskey_tokens",
	"gerudo_fortress",
	"hints",
	"keysanity",
	"lacs_condition",
	"lacs_hearts",
	"lacs_medallions",
	"lacs_rewards",
	"lacs_stones",
	"lacs_tokens",
	"logic_rules",
	"open_door_of_time",
	"open_forest",
	"open_kakariko",
	"plant_beans",
	"selected_adult_trade_item",
	"shuffle_dungeon_entrances",
	"shuffle_empty_pots",
	"shuffle_expensive_merchants",
	"shuffle_ganon_bosskey",
	"shuffle_gerudo_fortress_heart_piece",
	"shuffle_hideout_entrances",
	"shuffle_individual_ocarina_notes",
	"shuffle_interior_entrances",
	"shuffle_overworld_entrances",
	"shuffle_pots",
	"shuffle_scrubs",
	"shuffle_silver_rupees",
	"shuffle_tcgkeys",
	"skip_child_zelda",
	"skip_reward_from_rauru",
	"skipped_trials",
	"starting_age",
	"triforce_goal_per_world",
	"warp_songs",
	"zora_fountain",
}
