package components

// jq -Mr 'reduce .[] as $x ([]; . + $x.categories // []) | .[]' data/locations.json
type (
	Beehives               struct{}
	BottomoftheWell        struct{}
	BottomoftheWellMQ      struct{}
	Chests                 struct{}
	Cows                   struct{}
	Crates                 struct{}
	DeathMountain          struct{}
	DeathMountainCrater    struct{}
	DeathMountainTrail     struct{}
	DekuScrubs             struct{}
	DekuScrubUpgrades      struct{}
	DekuTree               struct{}
	DekuTreeMQ             struct{}
	DesertColossus         struct{}
	DodongosCavern         struct{}
	DodongosCavernMQ       struct{}
	DungeonRewards         struct{}
	FireTemple             struct{}
	FireTempleMQ           struct{}
	FlyingPots             struct{}
	Forest                 struct{}
	ForestArea             struct{}
	ForestTemple           struct{}
	ForestTempleMQ         struct{}
	Freestandings          struct{}
	GanonsCastle           struct{}
	GanonsCastleMQ         struct{}
	GanonsTower            struct{}
	Gerudo                 struct{}
	GerudosFortress        struct{}
	GerudoTrainingGround   struct{}
	GerudoTrainingGroundMQ struct{}
	GerudoValley           struct{}
	GoldSkulltulas         struct{}
	GoronCity              struct{}
	Graveyard              struct{}
	GreatFairies           struct{}
	Grottos                struct{}
	HauntedWasteland       struct{}
	HyruleCastle           struct{}
	HyruleField            struct{}
	IceCavern              struct{}
	IceCavernMQ            struct{}
	JabuJabusBelly         struct{}
	JabuJabusBellyMQ       struct{}
	Kakariko               struct{}
	KakarikoVillage        struct{}
	KokiriForest           struct{}
	LakeHylia              struct{}
	LonLonRanch            struct{}
	LostWoods              struct{}
	Market                 struct{}
	MasterQuest            struct{}
	Minigames              struct{}
	NeedSpiritualStones    struct{}
	NPCs                   struct{}
	OutsideGanonsCastle    struct{}
	Pots                   struct{}
	RupeeTowers            struct{}
	SacredForestMeadow     struct{}
	ShadowTemple           struct{}
	ShadowTempleMQ         struct{}
	Shops                  struct{}
	SilverRupees           struct{}
	SkulltulaHouse         struct{}
	SmallCrates            struct{}
	Songs                  struct{}
	SpiritTemple           struct{}
	SpiritTempleMQ         struct{}
	TempleofTime           struct{}
	ThievesHideout         struct{}
	VanillaDungeons        struct{}
	WaterTemple            struct{}
	WaterTempleMQ          struct{}
	Wonderitem             struct{}
	ZorasDomain            struct{}
	ZorasFountain          struct{}
	ZorasRiver             struct{}
)
