package components

// jq -Mr 'reduce .[] as $x ([]; . + $x.categories // []) | .[]' data/locations.json
type (
	DefaultItem          string
	RecoveryHeart        struct{}
	ActorOverride        struct{}
	Beehive              struct{}
	Boss                 struct{}
	BossHeart            struct{}
	BottomOfTheWell      struct{}
	Chest                struct{}
	Collectable          struct{}
	Cow                  struct{}
	Crate                struct{}
	Cutscene             struct{}
	DeathMountainCrater  struct{}
	DeathMountainTrail   struct{}
	DekuScrub            struct{}
	DekuScrubUpgrade     struct{}
	DekuTree             struct{}
	DesertColossus       struct{}
	DodongosCavern       struct{}
	FireTemple           struct{}
	Flying               struct{}
	ForestArea           struct{}
	ForestTemple         struct{}
	Freestanding         struct{}
	GanonsCastle         struct{}
	GanonsTower          struct{}
	GerudoTrainingGround struct{}
	GerudoValley         struct{}
	GerudosFortress      struct{}
	GoldSkulltula        struct{}
	GoronCity            struct{}
	Graveyard            struct{}
	GreatFairie          struct{}
	Grotto               struct{}
	GrottoScrub          struct{}
	HauntedWasteland     struct{}
	Hint                 struct{}
	HintStone            struct{}
	HyruleCastle         struct{}
	HyruleField          struct{}
	IceCavern            struct{}
	JabuJabusBelly       struct{}
	KakarikoVillage      struct{}
	KokiriForest         struct{}
	LakeHylia            struct{}
	LonLonRanch          struct{}
	LostWoods            struct{}
	Market               struct{}
	MasterQuest          struct{}
	Minigame             struct{}
	NPC                  struct{}
	NeedSpiritualStones  struct{}
	OutsideGanonsCastle  struct{}
	Pot                  struct{}
	RupeeTower           struct{}
	SacredForestMeadow   struct{}
	Scrub                struct{}
	ShadowTemple         struct{}
	Shop                 struct{}
	SkulltulaHouse       struct{}
	SmallCrate           struct{}
	SpiritTemple         struct{}
	TempleofTime         struct{}
	ThievesHideout       struct{}
	VanillaDungeon       struct{}
	WaterTemple          struct{}
	ZorasDomain          struct{}
	ZorasFountain        struct{}
	ZorasRiver           struct{}
)
