package components

// jq -Mr 'reduce .[] as $x ([]; . + $x.categories // []) | .[]' inputs/data/locations.json
type (
	Beehive                struct{}
	Boss                   struct{}
	BossHeart              struct{}
	BottomoftheWell        struct{}
	BottomoftheWellMQ      struct{}
	Chest                  struct{}
	Cows                   struct{}
	Crate                  struct{}
	Cutscene               struct{}
	DeathMountain          struct{}
	DeathMountainCrater    struct{}
	DeathMountainTrail     struct{}
	DekuScrubUpgrades      struct{}
	DekuScrubs             struct{}
	DekuTree               struct{}
	DekuTreeMQ             struct{}
	DesertColossus         struct{}
	Dungeon                string
	DodongosCavern         struct{}
	DodongosCavernMQ       struct{}
	FireTemple             struct{}
	FireTempleMQ           struct{}
	FlyingPot              struct{}
	Forest                 struct{}
	ForestArea             struct{}
	ForestTemple           struct{}
	ForestTempleMQ         struct{}
	Freestanding           struct{}
	GanonsCastle           struct{}
	GanonsCastleMQ         struct{}
	GanonsTower            struct{}
	Gerudo                 struct{}
	GerudoTrainingGround   struct{}
	GerudoTrainingGroundMQ struct{}
	GerudoValley           struct{}
	GerudosFortress        struct{}
	GoldSkulltulas         struct{}
	GoronCity              struct{}
	Graveyard              struct{}
	GreatFairies           struct{}
	GrottoScrub            struct{}
	Grottos                struct{}
	HauntedWasteland       struct{}
	Hint                   struct{}
	HintStone              struct{}
	HyruleCastle           struct{}
	HyruleField            struct{}
	IceCavern              struct{}
	IceCavernMQ            struct{}
	JabuJabusBelly         struct{}
	JabuJabusBellyMQ       struct{}
	Kakariko               struct{}
	KakarikoVillage        struct{}
	KokiriForest           struct{}
	LakeHylia              struct{}
	LonLonRanch            struct{}
	LostWoods              struct{}
	Market                 struct{}
	MaskShop               struct{}
	MasterQuest            struct{}
	Minigames              struct{}
	NPC                    struct{}
	NeedSpiritualStones    struct{}
	OutsideGanonsCastle    struct{}
	Pot                    struct{}
	RupeeTower             struct{}
	SacredForestMeadow     struct{}
	Scrub                  struct{}
	ShadowTemple           struct{}
	ShadowTempleMQ         struct{}
	Shop                   struct{}
	SilverRupee            struct{}
	SkulltulaHouse         struct{}
	SmallCrate             struct{}
	SpiritTemple           struct{}
	SpiritTempleMQ         struct{}
	TempleofTime           struct{}
	ThievesHideout         struct{}
	VanillaDungeons        struct{}
	WaterTemple            struct{}
	WaterTempleMQ          struct{}
	Wonderitem             struct{}
	ZorasDomain            struct{}
	ZorasFountain          struct{}
	ZorasRiver             struct{}
)
